name: CI Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run ESLint
        run: npx eslint . --max-warnings=0

      - name: Run audit
        run: npm audit --audit-level=high

      - name: Build (frontend only)
        if: contains(github.repository, 'frontend')
        run: npm run build
